sonar.projectKey=Ksr958_Nueve
sonar.organization=ksr958

sonar.sources=backend,frontend/app
sonar.exclusions=**/node_modules/**,**/migrations/**,**/.next/**
sonar.coverage.exclusions=backend/**,frontend/app/**/*.jsx,frontend/app/**/page.js,frontend/app/**/layout.jsx,frontend/app/components/**,frontend/app/contexts/**,frontend/app/services/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
