sonar.projectKey=Ksr958_Nueve
sonar.organization=ksr958

sonar.sources=backend,frontend/app
sonar.exclusions=**/node_modules/**,**/migrations/**,**/.next/**
sonar.coverage.inclusions=frontend/app/utils/apis.js
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
