# Generated by Django 5.2.11 on 2026-04-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedemployee',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='photo',
        ),
    ]
